# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setStyleSheet("*{\n"
"    background:  #1B1B1B;\n"
"    color: white;\n"
"}\n"
"QPushButton{\n"
"    background-color: transparent;\n"
"    border: 1px solid #E5A00D;\n"
"    color: #E5A00D;\n"
"    border-radius: 20px;\n"
"    font-size: 16px;\n"
"    height: 21px;\n"
"    width: 104px;\n"
"    padding: 10px 18px;\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"    font-size:16px;\n"
"}\n"
"\n"
"#dlg_title{\n"
"    font-size: 28px}\n"
"\n"
"#centralwidget{\n"
"    background-color: #202020;\n"
"}\n"
"#leftMenuContainer{\n"
"    background-color: #1B1B1B;\n"
"}\n"
"\n"
"#btn_dlg{\n"
"    background-color: #1B1B1B;\n"
"    border: 6px solid #1B1B1B;\n"
"    border-radius: 6px;\n"
"    color: #BABABA;\n"
"    font-size: 16px;\n"
"    text-align: left;\n"
"}\n"
"#btn_home_page{\n"
"    background-color: black;\n"
"    border: 6px solid black;\n"
"    border-radius: 6px;\n"
"    color: #E5A00D;\n"
"    font-size: 16px;\n"
"    text-align: left;\n"
"}\n"
"\n"
"#btn_plex_download, #btn_plex_upload, #btn_plex_update, #btn_spotify_download, #btn_spotify_upload, #btn_spotify_update{\n"
"    background-color: transparent;\n"
"    color: #BABABA;\n"
"    border: 1px solid #51391B;\n"
"    border-radius: 20px;\n"
"    font-size: 16px;\n"
"    height: 21px;\n"
"    width: 104px;\n"
"    padding: 10px 18px;\n"
"}\n"
"#btn_plex_connect, #btn_spotify_connect{ \n"
"    background-color: #51391B;\n"
"    color: #BABABA;\n"
"    border-radius: 20px;\n"
"    font-size: 16px;\n"
"    height: 21px;\n"
"    width: 130px;\n"
"    padding: 10px 18px;\n"
"}\n"
"\n"
"#cmb_library_prepend, #cmb_library_sections, #cmb_spotify_prepend{\n"
"    background-color: #272727;\n"
"}\n"
"#btn_playlist_convert, #btn_playlist_combine, #btn_tutorial{\n"
"    background-color: transparent;\n"
"    border: 1px solid #E5A00D;\n"
"    color: #E5A00D;\n"
"    border-radius: 20px;\n"
"    font-size: 16px;\n"
"    height: 21px;\n"
"    width: 104px;\n"
"    padding: 10px 18px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dlg_title = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dlg_title.sizePolicy().hasHeightForWidth())
        self.dlg_title.setSizePolicy(sizePolicy)
        self.dlg_title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.dlg_title.setObjectName("dlg_title")
        self.verticalLayout.addWidget(self.dlg_title)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dlg_msg = QtWidgets.QLabel(self.frame_3)
        self.dlg_msg.setObjectName("dlg_msg")
        self.verticalLayout_2.addWidget(self.dlg_msg, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_dlg_ok = QtWidgets.QPushButton(self.frame_4)
        self.btn_dlg_ok.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btn_dlg_ok.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_dlg_ok.setObjectName("btn_dlg_ok")
        self.horizontalLayout.addWidget(self.btn_dlg_ok, 0, QtCore.Qt.AlignHCenter)
        self.btn_dlg_cancel = QtWidgets.QPushButton(self.frame_4)
        self.btn_dlg_cancel.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btn_dlg_cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_dlg_cancel.setObjectName("btn_dlg_cancel")
        self.horizontalLayout.addWidget(self.btn_dlg_cancel, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.horizontalLayout_2.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.dlg_title.setText(_translate("Dialog", "Title"))
        self.dlg_msg.setText(_translate("Dialog", "Message for user goes here"))
        self.btn_dlg_ok.setText(_translate("Dialog", "Ok"))
        self.btn_dlg_cancel.setText(_translate("Dialog", "Cancel"))
